# -*- coding: utf-8 -*-
"""simpleChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdgihANcHAqVG68kcd8N73zFjOHPGHGA
"""

import nltk
from nltk.stem.lancaster import LancasterStemmer
# nltk.download('punkt')
stemmer = LancasterStemmer()

import numpy as np
import random
import json
import tensorflow
import tflearn
import pickle


with open("intents.json") as file:
    data = json.load(file)


try:
    with open("data.pickle", "rb") as f:
        words, labels, training, output = pickle.load(f)
except:

    words = []
    labels = []
    docsx = []
    docsy = []

    for intent in data['intents']:
      for pattern in intent['patterns']:
        wrds = nltk.word_tokenize(pattern)
        words.extend(wrds)
        docsx.append(wrds)
        docsy.append(intent['tag'])

      if(intent['tag'] not in labels):
        labels.append(intent['tag'])

    words = [stemmer.stem(w.lower()) for w in words if w != '?']
    words = sorted(list(set(words)))
    labels = sorted(labels)


    training = []
    output = []

    out_empty = [0 for _ in range(len(labels))]

    # print(out_empty)

    # print(words)
    # print(docsx)

    # print(len(words))

    for x, doc in enumerate(docsx):
      bag = []

      wrds = [stemmer.stem(w) for w in doc]

      for w in words:
        if w in wrds:
          bag.append(1)
        else:
          bag.append(0)

      outputrow = out_empty[:]
      outputrow[labels.index(docsy[x])] = 1

      training.append(bag)
      output.append(outputrow)


    # print(labels)
    # print(training)
    # print(output)
    # print(docsx)
    # print(docsy)

    training = np.array(training)
    output = np.array(output)

    with open("data.pickle", "wb") as f:
        pickle.dump((words, labels, training, output), f)



tensorflow.reset_default_graph()
net = tflearn.input_data(shape=[None, len(training[0])])
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, 8)
net = tflearn.fully_connected(net, len(output[0]), activation="softmax")
net = tflearn.regression(net)

model = tflearn.DNN(net)

try:
    model.load("model.tflearn")
except:
    model.fit(training, output, n_epoch=1000, batch_size=8, show_metric=True)
    model.save("model.tflearn")


def bag_of_words(s, words):
    bag = [0 for _ in range(len(words))]

    s_words = nltk.word_tokenize(s)
    s_words = [stemmer.stem(word.lower()) for word in s_words]

    for se in s_words:
        for i, w in enumerate(words):
            if w == se:
                bag[i] = 1
            
    return np.array(bag)


def chat():
    print("Start talking with the bot (type quit to stop)!")
    while True:
        inp = input("You: ")
        if inp.lower() == "quit":
            break

        results = model.predict([bag_of_words(inp, words)])
        results_index = np.argmax(results)
        tag = labels[results_index]

        for tg in data["intents"]:
            if tg['tag'] == tag:
                responses = tg['responses']

        print(random.choice(responses))

chat()

